Added HPLC Reader (as tar archive)
ComPlat/chemotion-converter-app pull request #102
Opened 2024-05-27 11:56 UTC by StarmanMartin

reades Data (no Metadata) from hplc file set. set has to be send as tar archive
[X15291.D.tar.gz](https://github.com/ComPlat/chemotion-converter-app/files/15455485/X15291.D.tar.gz)
[X15294.D.tar.gz](https://github.com/ComPlat/chemotion-converter-app/files/15455486/X15294.D.tar.gz)

close #101

2024-05-28 08:59 UTC, herrdivad commented
Do you please have a test server?
https://converter.martin-starman.com/admin/ ist not working:
![grafik](https://github.com/ComPlat/chemotion-converter-app/assets/113030128/a6231a9a-2e2f-49e4-8632-930edc7200e2)

2024-05-31 10:33 UTC, StarmanMartin commented
Can be tested [here](https://converter.martin-starman.com/admin/)

2024-06-05 06:35 UTC, herrdivad approved these changes

2024-07-08 09:21 UTC, herrdivad commented
The profile can be downloaded here:
[3c2426f0-46d2-415d-a752-b7f48eb0503c(2).json](https://github.com/user-attachments/files/16125439/3c2426f0-46d2-415d-a752-b7f48eb0503c.2.json)

2024-11-05 16:34 UTC, PiTrem requested changes
Could one clean the commit history as most of the visible changes are unrelated?

2024-11-05 16:34 UTC, PiTrem commented on requirements/common.txt
> +parser-binary @ git+https://github.com/ComPlat/BinaryParser@main
does this install the binary artifact from the repo or does this trigger the building from the source ?

2024-11-05 16:34 UTC, PiTrem commented on requirements/common.txt
> +parser-binary @ git+https://github.com/ComPlat/BinaryParser@main
What dependencies are needed at runtime ? Does the Readme needs an update

2024-12-16 15:23 UTC, headri commented
This reader throws an error if the tar/gz file contains no folder

2025-01-29 07:49 UTC, StarmanMartin commented on requirements/common.txt
> +parser-binary @ git+https://github.com/ComPlat/BinaryParser@main
Done

2025-02-04 10:05 UTC, PiTrem approved these changes

2025-02-04 10:13 UTC, PiTrem commented on output.txt
Is this file needed?

2025-02-04 10:18 UTC, PiTrem requested changes

2025-02-04 10:18 UTC, PiTrem commented on output.txt
Is this file needed?

2025-02-07 08:28 UTC, StarmanMartin commented on output.txt
Sorry my mistake ;). I removed the file

2025-02-10 15:14 UTC, merged