New reader for .asc files
ComPlat/chemotion-converter-app pull request #42
Opened 2023-02-24 09:08 UTC by phuang26

Asc files will be transmitted as bundled zip archives. The reader unzips the files and reads them as collective

2023-02-27 13:17 UTC, jochenklar commented
Is this a duplicate of #41? I am a bit confused.

2023-02-27 13:55 UTC, jochenklar requested changes
For some reason, the data arrays end up in the table metadata, is that on purpose?

![image](https://user-images.githubusercontent.com/1799675/221582186-560de920-7a95-487f-9265-617f88975449.png)

2023-02-27 13:55 UTC, jochenklar commented on converter_app/readers/asc_zip.py
> +        return tables
Here the column/rows count is missing:

```
table['metadata']['rows'] = str(len(table['rows']))
table['metadata']['columns'] = str(len(table['columns']))
```

2023-02-27 13:55 UTC, jochenklar commented on converter_app/readers/asc_zip.py
> +        metadata["wavelength [nm]"] = results[0]["Wavelength [nm]"]
should be casted to `str()` here:

```
metadata["wavelength [nm]"] = str(results[0]["Wavelength [nm]"])
```

2023-02-27 13:55 UTC, jochenklar commented on converter_app/readers/asc_zip.py
> +        metadata["duration [s]"] = results[0]["Duration [s]"]
Should be casted to `str()` here:

```
metadata["duration [s]"] = str(results[0]["Duration [s]"])
```

2023-02-27 13:57 UTC, jochenklar commented
@phuang26 @StarmanMartin Ok, I added some remarks. But don't forget that the code is already on master, so I guess it would be best to just fix those things in master or yet another feature branch.

2023-03-29 08:04 UTC, StarmanMartin commented
Fixed all commends:
[Pull request fixes](https://github.com/ComPlat/chemotion-converter-app/pull/42/commits/a32d08f6766e664ecf5dc37ca60914dc71dfd037)

2023-03-29 08:07 UTC, merged